Fix: InteractionCreateEvent send message
nonebot/plugin-alconna pull request #68
Opened 2024-08-09 16:59 UTC by Decrabbityyy

2024-08-09 17:08 UTC, RF-Tar-Railt requested changes
elif target.extra.get(xxx):
else:

2024-08-10 12:52 UTC, Decrabbityyy commented
> elif target.extra.get(xxx): else:

在哪层，跟target.private那个if后面吗

2024-08-10 12:57 UTC, RF-Tar-Railt requested changes

2024-08-10 12:57 UTC, RF-Tar-Railt commented on src/nonebot_plugin_alconna/uniseg/adapters/qq/exporter.py
> +                )
这

2024-08-10 12:58 UTC, Decrabbityyy commented on src/nonebot_plugin_alconna/uniseg/adapters/qq/exporter.py
> +                )
这是给私聊留的，私聊发送消息的接口不一样

2024-08-10 12:58 UTC, Decrabbityyy commented on src/nonebot_plugin_alconna/uniseg/adapters/qq/exporter.py
> +                )
而且我也测不了私聊

2024-08-10 13:00 UTC, RF-Tar-Railt commented on src/nonebot_plugin_alconna/uniseg/adapters/qq/exporter.py
> +                )
我在说缩进啊

2024-08-10 13:02 UTC, RF-Tar-Railt commented on src/nonebot_plugin_alconna/uniseg/adapters/qq/exporter.py
> +                )
```python
         elif target.extra.get("qq.interaction", False): 
             res = await bot.send_to_group(group_openid=target.id, message=message, event_id=target.source, **kwargs) 
             return res 
         else: 
             res = await bot.send_to_group( 
                 group_openid=target.id, 
                 message=message, 
                 msg_id=target.source, 
                 msg_seq=target.extra["qq.reply_seq"], 
                 **kwargs, 
             )
```

2024-08-10 13:25 UTC, RF-Tar-Railt approved these changes

2024-08-10 13:26 UTC, merged